_wandb:
    value:
        cli_version: 0.22.3
        e:
            u2bmslmzpfu1keq7253c24xp9z833t8i:
                codePath: /Users/hochan.son/Project/MASDS/stats413/HW/HW3/STATS_413_HW3_CNN_HochanSon.ipynb
                codePathLocal: STATS_413_HW3_CNN_HochanSon.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "441000632320"
                        used: "297012674560"
                email: ohsono.email@gmail.com
                executable: /Users/hochan.son/Project/table-synthesizers/.conda/bin/python
                git:
                    commit: abbd35173d2a97d9414bc26f98e90595d9c0e4fc
                    remote: git@github.com:ohsono/stats413.git
                host: Hochans-MacBook-Pro-2019.local
                memory:
                    total: "17179869184"
                os: macOS-26.0.1-x86_64-i386-64bit
                program: /Users/hochan.son/Project/MASDS/stats413/HW/HW3/STATS_413_HW3_CNN_HochanSon.ipynb
                python: CPython 3.11.13
                root: /Users/hochan.son/Project/MASDS/stats413/HW/HW3
                startedAt: "2025-10-31T20:43:39.800464Z"
                writerId: u2bmslmzpfu1keq7253c24xp9z833t8i
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
            "2":
                - 1
                - 11
                - 41
                - 49
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.22.3
            "6": 4.56.2
            "8":
                - 1
                - 2
            "12": 0.22.3
            "13": darwin-x86_64
batch_size:
    value: 4
epochs:
    value: 20
learning_rate:
    value: 0.001
momentum:
    value: 0.9
